name: CI

on: push

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Extract tag
        id: extract-tag
        run: echo "::set-output name=tag::${GITHUB_REF/refs\/tags\//}"

      - name: Check tag
        run: echo ${{ steps.extract-tag.outputs.tag }}

      - name: Extract branch
        id: extract-branch
        run: echo "::set-output name=branch::${GITHUB_REF/refs\/heads\//}"

      - name: Check branch
        run: echo ${{ steps.extract-branch.outputs.branch }}

      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com

      - run: npm run bootstrap
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}

      - run: npm run build:all

      - run: npm run lint:all

      - run: npm run test:ci

  release:
    name: Create release
    needs: test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: false

  publish-npm:
    name: Publish NPM packages
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: release
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/

      - run: npm run bootstrap
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}

      - run: npm run build:all

      - run: npm publish packages/solid-crs-theme
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - run: npm publish packages/solid-crs-core
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - run: npm publish packages/solid-crs-components
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - run: npm publish packages/solid-crs-client
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  publish-docker:
    name: Publish Docker images
    needs: publish-npm
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - uses: actions/checkout@v2

      - name: Extract tag
        id: extract-tag
        run: echo "::set-output name=tag::${GITHUB_REF/refs\/tags\//}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PACKAGES_TOKEN }}

      - name: Build and push pods
        id: docker_build_pods
        uses: docker/build-push-action@v2
        with:
          context: packages/solid-crs-pods/
          push: true
          tags: |
            ghcr.io/netwerk-digitaal-erfgoed/solid-crs-pods:latest
            ghcr.io/netwerk-digitaal-erfgoed/solid-crs-pods:${{ steps.extract-tag.outputs.tag }}
          build-args: |
            NPM_TOKEN=${{secrets.GH_PACKAGES_TOKEN}}

      - name: Build and push manage
        id: docker_build_manage
        uses: docker/build-push-action@v2
        with:
          context: packages/solid-crs-manage/
          push: true
          tags: |
            ghcr.io/netwerk-digitaal-erfgoed/solid-crs-manage:latest
            ghcr.io/netwerk-digitaal-erfgoed/solid-crs-manage:${{ steps.extract-tag.outputs.tag }}

  deploy-develop:
    name: Deploy to develop
    needs: publish-docker
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - uses: actions/checkout@v2

      - name: Extract tag
        id: extract-tag
        run: echo "::set-output name=tag::${GITHUB_REF/refs\/tags\//}"

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PACKAGES_TOKEN }}

      - name: Deploy pods on develop
        uses: 'azure/aci-deploy@v1'
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          dns-name-label: solid-crs-pods-develop
          image: ghcr.io/netwerk-digitaal-erfgoed/solid-crs-pods:${{ steps.extract-tag.outputs.tag }}
          registry-login-server: ghcr.io
          registry-username: ${{ secrets.GA_USERNAME }}
          registry-password: ${{ secrets.GA_TOKEN }}
          name: solid-crs-pods-develop
          location: 'west europe'
          ports: 80
          command-line: ./node_modules/.bin/community-solid-server -b https://pods.nde.digita.ai -p 80 --rootFilePath /tmp/css -c config/config-file.json -l debug
          # ip-address: 'Private'

      - name: Deploy manage on develop
        uses: 'azure/aci-deploy@v1'
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          dns-name-label: solid-crs-manage-develop
          image: ghcr.io/netwerk-digitaal-erfgoed/solid-crs-manage:${{ steps.extract-tag.outputs.tag }}
          registry-login-server: ghcr.io
          registry-username: ${{ secrets.GA_USERNAME }}
          registry-password: ${{ secrets.GA_TOKEN }}
          name: solid-crs-manage-develop
          location: 'west europe'
          ports: 3002
          # ip-address: 'Private'
